version: '2'
services:
  jhipstermicroapplication-app:
    image: jhipstermicroapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermicroapplication-mysql:3306/jhipstermicroapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  jhipstermicroapplication-mysql:
    extends:
      file: mysql.yml
      service: jhipstermicroapplication-mysql
